package org.clapper.minecraft.EndlessDispenser

import org.clapper.minecraft.lib.MinecraftConstants
import org.bukkit.material.MaterialData
import org.bukkit.Material

/** Constants.
  */
private[EndlessDispenser] object Constants {
  val SchedulerInterval = 5 * MinecraftConstants.TicksPerMinute
  val EndlessLabel      = "<endless>"

  val MaterialMap = Map(
    "activator rail"       -> Material.ACTIVATOR_RAIL,
    "air"                  -> Material.AIR,
    "anvil"                -> Material.ANVIL,
    "apple"                -> Material.APPLE,
    "arrow"                -> Material.ARROW,
    "baked potato"         -> Material.BAKED_POTATO,
    "beacon"               -> Material.BEACON,
    "bed"                  -> Material.BED,
    "bedrock"              -> Material.BEDROCK,
    "birch wood stairs"    -> Material.BIRCH_WOOD_STAIRS,
    "blaze powder"         -> Material.BLAZE_POWDER,
    "blaze rod"            -> Material.BLAZE_ROD,
    "boat"                 -> Material.BOAT,
    "bone"                 -> Material.BONE,
    "book"                 -> Material.BOOK,
    "book and quill"       -> Material.BOOK_AND_QUILL,
    "bookshelf"            -> Material.BOOKSHELF,
    "bow"                  -> Material.BOW,
    "bowl"                 -> Material.BOWL,
    "bread"                -> Material.BREAD,
    "brewing stand"        -> Material.BREWING_STAND,
    "brick"                -> Material.BRICK,
    "brick stairs"         -> Material.BRICK_STAIRS,
    "brown mushroom"       -> Material.BROWN_MUSHROOM,
    "bucket"               -> Material.BUCKET,
    "cactus"               -> Material.CACTUS,
    "cake"                 -> Material.CAKE,
    "carpet"               -> Material.CARPET,
    "carrot"               -> Material.CARROT,
    "carrot stick"         -> Material.CARROT_STICK,
    "cauldron"             -> Material.CAULDRON,
    "chainmail boots"      -> Material.CHAINMAIL_BOOTS,
    "chainmail chestplate" -> Material.CHAINMAIL_CHESTPLATE,
    "chainmail helmet"     -> Material.CHAINMAIL_HELMET,
    "chainmail leggings"   -> Material.CHAINMAIL_LEGGINGS,
    "chest"                -> Material.CHEST,
    "clay"                 -> Material.CLAY,
    "clay ball"            -> Material.CLAY_BALL,
    "clay brick"           -> Material.CLAY_BRICK,
    "coal"                 -> Material.COAL,
    "coal ore"             -> Material.COAL_ORE,
    "cobble wall"          -> Material.COBBLE_WALL,
    "cobblestone"          -> Material.COBBLESTONE,
    "cobblestone stairs"   -> Material.COBBLESTONE_STAIRS,
    "cocoa"                -> Material.COCOA,
    "compass"              -> Material.COMPASS,
    "cooked beef"          -> Material.COOKED_BEEF,
    "cooked chicken"       -> Material.COOKED_CHICKEN,
    "cooked fish"          -> Material.COOKED_FISH,
    "cookie"               -> Material.COOKIE,
    "crops"                -> Material.CROPS,
    "daylight detector"    -> Material.DAYLIGHT_DETECTOR,
    "detector rail"        -> Material.DETECTOR_RAIL,
    "diamond"              -> Material.DIAMOND,
    "diamond axe"          -> Material.DIAMOND_AXE,
    "diamond barding"      -> Material.DIAMOND_BARDING,
    "diamond boots"        -> Material.DIAMOND_BOOTS,
    "diamond chestplate"   -> Material.DIAMOND_CHESTPLATE,
    "diamond helmet"       -> Material.DIAMOND_HELMET,
    "diamond hoe"          -> Material.DIAMOND_HOE,
    "diamond leggings"     -> Material.DIAMOND_LEGGINGS,
    "diamond ore"          -> Material.DIAMOND_ORE,
    "diamond pickaxe"      -> Material.DIAMOND_PICKAXE,
    "diamond spade"        -> Material.DIAMOND_SPADE,
    "diamond sword"        -> Material.DIAMOND_SWORD,
    "diode"                -> Material.DIODE,
    "dirt"                 -> Material.DIRT,
    "dispenser"            -> Material.DISPENSER,
    "dragon egg"           -> Material.DRAGON_EGG,
    "dropper"              -> Material.DROPPER,
    "egg"                  -> Material.EGG,
    "emerald"              -> Material.EMERALD,
    "emerald ore"          -> Material.EMERALD_ORE,
    "empty map"            -> Material.EMPTY_MAP,
    "enchanted book"       -> Material.ENCHANTED_BOOK,
    "enchantment table"    -> Material.ENCHANTMENT_TABLE,
    "ender chest"          -> Material.ENDER_CHEST,
    "ender pearl"          -> Material.ENDER_PEARL,
    "ender stone"          -> Material.ENDER_STONE,
    "exp bottle"           -> Material.EXP_BOTTLE,
    "eye of ender"         -> Material.EYE_OF_ENDER,
    "feather"              -> Material.FEATHER,
    "fence"                -> Material.FENCE,
    "fence gate"           -> Material.FENCE_GATE,
    "fermented spider eye" -> Material.FERMENTED_SPIDER_EYE,
    "firework"             -> Material.FIREWORK,
    "firework charge"      -> Material.FIREWORK_CHARGE,
    "fishing rod"          -> Material.FISHING_ROD,
    "flint"                -> Material.FLINT,
    "flint and steel"      -> Material.FLINT_AND_STEEL,
    "flower pot"           -> Material.FLOWER_POT,
    "furnace"              -> Material.FURNACE,
    "ghast tear"           -> Material.GHAST_TEAR,
    "glass"                -> Material.GLASS,
    "glass bottle"         -> Material.GLASS_BOTTLE,
    "glowstone"            -> Material.GLOWSTONE,
    "glowstone dust"       -> Material.GLOWSTONE_DUST,
    "gold axe"             -> Material.GOLD_AXE,
    "gold barding"         -> Material.GOLD_BARDING,
    "gold boots"           -> Material.GOLD_BOOTS,
    "gold chestplate"      -> Material.GOLD_CHESTPLATE,
    "gold helmet"          -> Material.GOLD_HELMET,
    "gold hoe"             -> Material.GOLD_HOE,
    "gold ingot"           -> Material.GOLD_INGOT,
    "gold leggings"        -> Material.GOLD_LEGGINGS,
    "gold nugget"          -> Material.GOLD_NUGGET,
    "gold ore"             -> Material.GOLD_ORE,
    "gold pickaxe"         -> Material.GOLD_PICKAXE,
    "gold plate"           -> Material.GOLD_PLATE,
    "gold record"          -> Material.GOLD_RECORD,
    "gold spade"           -> Material.GOLD_SPADE,
    "gold sword"           -> Material.GOLD_SWORD,
    "golden apple"         -> Material.GOLDEN_APPLE,
    "golden carrot"        -> Material.GOLDEN_CARROT,
    "grass"                -> Material.GRASS,
    "gravel"               -> Material.GRAVEL,
    "grilled pork"         -> Material.GRILLED_PORK,
    "hard clay"            -> Material.HARD_CLAY,
    "hopper"               -> Material.HOPPER,
    "ice"                  -> Material.ICE,
    "ink sack"             -> Material.INK_SACK,
    "iron axe"             -> Material.IRON_AXE,
    "iron barding"         -> Material.IRON_BARDING,
    "iron boots"           -> Material.IRON_BOOTS,
    "iron chestplate"      -> Material.IRON_CHESTPLATE,
    "iron door"            -> Material.IRON_DOOR,
    "iron fence"           -> Material.IRON_FENCE,
    "iron helmet"          -> Material.IRON_HELMET,
    "iron hoe"             -> Material.IRON_HOE,
    "iron ingot"           -> Material.IRON_INGOT,
    "iron leggings"        -> Material.IRON_LEGGINGS,
    "iron ore"             -> Material.IRON_ORE,
    "iron pickaxe"         -> Material.IRON_PICKAXE,
    "iron plate"           -> Material.IRON_PLATE,
    "iron spade"           -> Material.IRON_SPADE,
    "iron sword"           -> Material.IRON_SWORD,
    "item frame"           -> Material.ITEM_FRAME,
    "jukebox"              -> Material.JUKEBOX,
    "jungle wood stairs"   -> Material.JUNGLE_WOOD_STAIRS,
    "ladder"               -> Material.LADDER,
    "lapis ore"            -> Material.LAPIS_ORE,
    "lava bucket"          -> Material.LAVA_BUCKET,
    "leash"                -> Material.LEASH,
    "leather"              -> Material.LEATHER,
    "leather boots"        -> Material.LEATHER_BOOTS,
    "leather chestplate"   -> Material.LEATHER_CHESTPLATE,
    "leather helmet"       -> Material.LEATHER_HELMET,
    "leather leggings"     -> Material.LEATHER_LEGGINGS,
    "leaves"               -> Material.LEAVES,
    "lever"                -> Material.LEVER,
    "log"                  -> Material.LOG,
    "long grass"           -> Material.LONG_GRASS,
    "magma cream"          -> Material.MAGMA_CREAM,
    "map"                  -> Material.MAP,
    "melon"                -> Material.MELON,
    "melon seeds"          -> Material.MELON_SEEDS,
    "melon stem"           -> Material.MELON_STEM,
    "minecart"             -> Material.MINECART,
    "mob spawner"          -> Material.MOB_SPAWNER,
    "monster egg"          -> Material.MONSTER_EGG,
    "monster eggs"         -> Material.MONSTER_EGGS,
    "mossy cobblestone"    -> Material.MOSSY_COBBLESTONE,
    "mushroom soup"        -> Material.MUSHROOM_SOUP,
    "mycel"                -> Material.MYCEL,
    "name tag"             -> Material.NAME_TAG,
    "nether brick"         -> Material.NETHER_BRICK,
    "nether brick stairs"  -> Material.NETHER_BRICK_STAIRS,
    "nether fence"         -> Material.NETHER_FENCE,
    "nether stalk"         -> Material.NETHER_STALK,
    "nether star"          -> Material.NETHER_STAR,
    "nether warts"         -> Material.NETHER_WARTS,
    "netherrack"           -> Material.NETHERRACK,
    "obsidian"             -> Material.OBSIDIAN,
    "painting"             -> Material.PAINTING,
    "paper"                -> Material.PAPER,
    "piston"               -> Material.PISTON_BASE,
    "poisonous potato"     -> Material.POISONOUS_POTATO,
    "pork"                 -> Material.PORK,
    "portal"               -> Material.PORTAL,
    "potato"               -> Material.POTATO,
    "potion"               -> Material.POTION,
    "powered minecart"     -> Material.POWERED_MINECART,
    "powered rail"         -> Material.POWERED_RAIL,
    "pumpkin"              -> Material.PUMPKIN,
    "pumpkin pie"          -> Material.PUMPKIN_PIE,
    "pumpkin seeds"        -> Material.PUMPKIN_SEEDS,
    "pumpkin stem"         -> Material.PUMPKIN_STEM,
    "quartz"               -> Material.QUARTZ,
    "quartz ore"           -> Material.QUARTZ_ORE,
    "quartz stairs"        -> Material.QUARTZ_STAIRS,
    "rails"                -> Material.RAILS,
    "raw beef"             -> Material.RAW_BEEF,
    "raw chicken"          -> Material.RAW_CHICKEN,
    "raw fish"             -> Material.RAW_FISH,
    "record 10"            -> Material.RECORD_10,
    "record 11"            -> Material.RECORD_11,
    "record 12"            -> Material.RECORD_12,
    "record 3"             -> Material.RECORD_3,
    "record 4"             -> Material.RECORD_4,
    "record 5"             -> Material.RECORD_5,
    "record 6"             -> Material.RECORD_6,
    "record 7"             -> Material.RECORD_7,
    "record 8"             -> Material.RECORD_8,
    "record 9"             -> Material.RECORD_9,
    "red mushroom"         -> Material.RED_MUSHROOM,
    "red rose"             -> Material.RED_ROSE,
    "redstone"             -> Material.REDSTONE,
    "redstone comparator"  -> Material.REDSTONE_COMPARATOR,
    "redstone ore"         -> Material.REDSTONE_ORE,
    "redstone wire"        -> Material.REDSTONE_WIRE,
    "rotten flesh"         -> Material.ROTTEN_FLESH,
    "saddle"               -> Material.SADDLE,
    "sand"                 -> Material.SAND,
    "sandstone"            -> Material.SANDSTONE,
    "sandstone stairs"     -> Material.SANDSTONE_STAIRS,
    "sapling"              -> Material.SAPLING,
    "seeds"                -> Material.SEEDS,
    "shears"               -> Material.SHEARS,
    "sign"                 -> Material.SIGN,
    "sign post"            -> Material.SIGN_POST,
    "skull"                -> Material.SKULL,
    "slime ball"           -> Material.SLIME_BALL,
    "smooth brick"         -> Material.SMOOTH_BRICK,
    "smooth stairs"        -> Material.SMOOTH_STAIRS,
    "snow"                 -> Material.SNOW,
    "snow ball"            -> Material.SNOW_BALL,
    "soil"                 -> Material.SOIL,
    "soul sand"            -> Material.SOUL_SAND,
    "speckled melon"       -> Material.SPECKLED_MELON,
    "spider eye"           -> Material.SPIDER_EYE,
    "sponge"               -> Material.SPONGE,
    "spruce wood stairs"   -> Material.SPRUCE_WOOD_STAIRS,
    "stained clay"         -> Material.STAINED_CLAY,
    "stationary lava"      -> Material.STATIONARY_LAVA,
    "stationary water"     -> Material.STATIONARY_WATER,
    "step"                 -> Material.STEP,
    "stick"                -> Material.STICK,
    "sticky piston"        -> Material.PISTON_STICKY_BASE,
    "stone"                -> Material.STONE,
    "stone axe"            -> Material.STONE_AXE,
    "stone button"         -> Material.STONE_BUTTON,
    "stone hoe"            -> Material.STONE_HOE,
    "stone pickaxe"        -> Material.STONE_PICKAXE,
    "stone plate"          -> Material.STONE_PLATE,
    "stone spade"          -> Material.STONE_SPADE,
    "stone sword"          -> Material.STONE_SWORD,
    "storage minecart"     -> Material.STORAGE_MINECART,
    "string"               -> Material.STRING,
    "sugar"                -> Material.SUGAR,
    "sugar cane"           -> Material.SUGAR_CANE,
    "sulphur"              -> Material.SULPHUR,
    "thin glass"           -> Material.THIN_GLASS,
    "tnt"                  -> Material.TNT,
    "torch"                -> Material.TORCH,
    "trap door"            -> Material.TRAP_DOOR,
    "trapped chest"        -> Material.TRAPPED_CHEST,
    "tripwire"             -> Material.TRIPWIRE,
    "tripwire hook"        -> Material.TRIPWIRE_HOOK,
    "vine"                 -> Material.VINE,
    "wall sign"            -> Material.WALL_SIGN,
    "watch"                -> Material.WATCH,
    "water"                -> Material.WATER,
    "water bucket"         -> Material.WATER_BUCKET,
    "water lily"           -> Material.WATER_LILY,
    "web"                  -> Material.WEB,
    "wheat"                -> Material.WHEAT,
    "wood"                 -> Material.WOOD,
    "wood axe"             -> Material.WOOD_AXE,
    "wood button"          -> Material.WOOD_BUTTON,
    "wood door"            -> Material.WOOD_DOOR,
    "wood double step"     -> Material.WOOD_DOUBLE_STEP,
    "wood hoe"             -> Material.WOOD_HOE,
    "wood pickaxe"         -> Material.WOOD_PICKAXE,
    "wood plate"           -> Material.WOOD_PLATE,
    "wood spade"           -> Material.WOOD_SPADE,
    "wood stairs"          -> Material.WOOD_STAIRS,
    "wood step"            -> Material.WOOD_STEP,
    "wood sword"           -> Material.WOOD_SWORD,
    "wooden door"          -> Material.WOODEN_DOOR,
    "wool"                 -> Material.WOOL,
    "workbench"            -> Material.WORKBENCH,
    "written book"         -> Material.WRITTEN_BOOK,
    "yellow flower"        -> Material.YELLOW_FLOWER
  )
}

